/**
 * Roc Platform ABI Header
 *
 * This file defines C declarations for a Roc platform's direct symbol ABI.
 * It is automatically generated by the Roc glue generator.
 *
 * Hosted argument ownership:
 * Roc transfers ownership of refcounted arguments to the hosted function.
 * The hosted function must release owned refcounted arguments when done,
 * or retain/transfer ownership explicitly when storing or returning them.
 * Releasing a container releases its elements only when the container's own
 * count reaches zero, which is what compiled Roc code does when it drops one
 * it owns. Releasing the elements unconditionally double-frees them whenever
 * the Roc caller still holds the container.
 */

#ifndef ROC_PLATFORM_ABI_H
#define ROC_PLATFORM_ABI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if defined(__cplusplus)
#define ROC_ALIGNAS(n) alignas(n)
#define ROC_ALIGNOF(T) alignof(T)
#define ROC_STATIC_ASSERT(cond, message) static_assert(cond, message)
#else
#define ROC_ALIGNAS(n) _Alignas(n)
#define ROC_ALIGNOF(T) _Alignof(T)
#define ROC_STATIC_ASSERT(cond, message) _Static_assert(cond, message)
#endif

static inline void roc_abi_copy_bytes(void* dst, const void* src, size_t count) {
    uint8_t* dst_bytes = (uint8_t*)dst;
    const uint8_t* src_bytes = (const uint8_t*)src;
    for (size_t index = 0; index < count; index++) {
        dst_bytes[index] = src_bytes[index];
    }
}

#ifdef __cplusplus
extern "C" {
#endif

// Core Roc Types

typedef struct {
    __int128 num;
} RocDec;

ROC_STATIC_ASSERT(sizeof(RocDec) == 16, "RocDec must be sixteen bytes");
ROC_STATIC_ASSERT(ROC_ALIGNOF(RocDec) == 16, "RocDec must be 16-byte aligned");

#if defined(_MSC_VER) && !defined(__clang__) && defined(_M_X64)
#include <intrin.h>
typedef __m128i RocU8x16;
typedef __m128i RocI8x16;
typedef __m128i RocU16x8;
typedef __m128i RocI16x8;
typedef __m128i RocU32x4;
typedef __m128i RocI32x4;
typedef __m128i RocU64x2;
typedef __m128i RocI64x2;
#elif defined(_MSC_VER) && !defined(__clang__) && defined(_M_ARM64)
#include <arm64_neon.h>
typedef uint8x16_t RocU8x16;
typedef int8x16_t RocI8x16;
typedef uint16x8_t RocU16x8;
typedef int16x8_t RocI16x8;
typedef uint32x4_t RocU32x4;
typedef int32x4_t RocI32x4;
typedef uint64x2_t RocU64x2;
typedef int64x2_t RocI64x2;
#elif defined(__aarch64__)
#include <arm_neon.h>
typedef uint8x16_t RocU8x16;
typedef int8x16_t RocI8x16;
typedef uint16x8_t RocU16x8;
typedef int16x8_t RocI16x8;
typedef uint32x4_t RocU32x4;
typedef int32x4_t RocI32x4;
typedef uint64x2_t RocU64x2;
typedef int64x2_t RocI64x2;
#elif defined(__wasm_simd128__)
#include <wasm_simd128.h>
typedef v128_t RocU8x16;
typedef v128_t RocI8x16;
typedef v128_t RocU16x8;
typedef v128_t RocI16x8;
typedef v128_t RocU32x4;
typedef v128_t RocI32x4;
typedef v128_t RocU64x2;
typedef v128_t RocI64x2;
#else
typedef uint8_t RocU8x16 __attribute__((vector_size(16)));
typedef int8_t RocI8x16 __attribute__((vector_size(16)));
typedef uint16_t RocU16x8 __attribute__((vector_size(16)));
typedef int16_t RocI16x8 __attribute__((vector_size(16)));
typedef uint32_t RocU32x4 __attribute__((vector_size(16)));
typedef int32_t RocI32x4 __attribute__((vector_size(16)));
typedef uint64_t RocU64x2 __attribute__((vector_size(16)));
typedef int64_t RocI64x2 __attribute__((vector_size(16)));
#endif

#define ROC_ASSERT_VECTOR(T) ROC_STATIC_ASSERT(sizeof(T) == 16, #T " size mismatch"); ROC_STATIC_ASSERT(ROC_ALIGNOF(T) == 16, #T " alignment mismatch")
ROC_ASSERT_VECTOR(RocU8x16);
ROC_ASSERT_VECTOR(RocI8x16);
ROC_ASSERT_VECTOR(RocU16x8);
ROC_ASSERT_VECTOR(RocI16x8);
ROC_ASSERT_VECTOR(RocU32x4);
ROC_ASSERT_VECTOR(RocI32x4);
ROC_ASSERT_VECTOR(RocU64x2);
ROC_ASSERT_VECTOR(RocI64x2);
#undef ROC_ASSERT_VECTOR

typedef struct {
    uint8_t* bytes;
    size_t capacity_or_alloc_ptr;
    size_t length;
} RocStr;

ROC_STATIC_ASSERT(sizeof(RocStr) == 3 * sizeof(size_t), "RocStr must be three pointer-sized words");
ROC_STATIC_ASSERT(ROC_ALIGNOF(RocStr) == ROC_ALIGNOF(size_t), "RocStr must be pointer-word aligned");
ROC_STATIC_ASSERT(offsetof(RocStr, bytes) == 0, "RocStr.bytes offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocStr, capacity_or_alloc_ptr) == sizeof(size_t), "RocStr.capacity_or_alloc_ptr offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocStr, length) == 2 * sizeof(size_t), "RocStr.length offset mismatch");

typedef struct {
    void* elements;
    size_t length;
    size_t capacity_or_alloc_ptr;
} RocList;

ROC_STATIC_ASSERT(sizeof(RocList) == 3 * sizeof(size_t), "RocList must be three pointer-sized words");
ROC_STATIC_ASSERT(ROC_ALIGNOF(RocList) == ROC_ALIGNOF(size_t), "RocList must be pointer-word aligned");
ROC_STATIC_ASSERT(offsetof(RocList, elements) == 0, "RocList.elements offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocList, length) == sizeof(size_t), "RocList.length offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocList, capacity_or_alloc_ptr) == 2 * sizeof(size_t), "RocList.capacity_or_alloc_ptr offset mismatch");

typedef void* RocBox;

struct RocOps;

/* `reuse` is nullable. Non-null must be the callable data pointer whose inline capture begins at `capture`; it transfers one owned reference to the callee. The caller must not use or decref that ownership unit after the call. The callee consumes it exactly once, whether or not the result can reuse the allocation. */
typedef void (*RocErasedCallableFn)(struct RocOps* ops, uint8_t* ret, const uint8_t* args, uint8_t* capture, uint8_t* reuse, const void** ret_desc);
typedef void (*RocErasedCallableOnDrop)(uint8_t* capture, struct RocOps* ops);
typedef struct {
    RocErasedCallableFn callable_fn_ptr;
    RocErasedCallableOnDrop on_drop;
} RocErasedCallablePayload;
ROC_STATIC_ASSERT(offsetof(RocErasedCallablePayload, callable_fn_ptr) == 0, "RocErasedCallablePayload.callable_fn_ptr offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocErasedCallablePayload, on_drop) == sizeof(RocErasedCallableFn), "RocErasedCallablePayload.on_drop offset mismatch");
typedef uint8_t* RocErasedCallable;
#define ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT 16u
#define ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT 16u
#define ROC_ERASED_CALLABLE_CAPTURE_OFFSET ((sizeof(RocErasedCallablePayload) + 15u) & ~15u)
#define ROC_ERASED_CALLABLE_PAYLOAD_SIZE(capture_size) (ROC_ERASED_CALLABLE_CAPTURE_OFFSET + (capture_size))
static inline RocErasedCallablePayload* roc_erased_callable_payload_ptr(RocErasedCallable callable) {
    return (RocErasedCallablePayload*)callable;
}
static inline uint8_t* roc_erased_callable_capture_ptr(RocErasedCallable callable) {
    return callable == 0 ? 0 : callable + ROC_ERASED_CALLABLE_CAPTURE_OFFSET;
}


// Reflected Roc Types

typedef struct Try Try;

typedef uint8_t TryTag;
enum {
    TryTag_Err = 0,
    TryTag_Ok = 1
};
typedef union {
    int32_t err;
    uint8_t ok;
} TryTagPayloadStorage;
#if UINTPTR_MAX == UINT64_MAX
struct Try {
    TryTagPayloadStorage payload;
    TryTag tag;
};
ROC_STATIC_ASSERT(sizeof(Try) == 8, "Try size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(Try) == 4, "Try alignment mismatch");
ROC_STATIC_ASSERT(offsetof(Try, tag) == 4, "Try.tag offset mismatch");
#else
struct Try {
    ROC_ALIGNAS(4) uint8_t payload[4];
    TryTag tag;
};
ROC_STATIC_ASSERT(sizeof(Try) == 8, "Try size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(Try) == 4, "Try alignment mismatch");
ROC_STATIC_ASSERT(offsetof(Try, tag) == 4, "Try.tag offset mismatch");
#endif
static inline Try Try_make_err(int32_t payload) {
    Try out = {0};
    out.tag = TryTag_Err;
#if UINTPTR_MAX == UINT64_MAX
    out.payload.err = payload;
#else
    roc_abi_copy_bytes(out.payload, &payload, sizeof(payload));
#endif
    return out;
}

static inline Try Try_make_ok(void) {
    Try out = {0};
    out.tag = TryTag_Ok;
    return out;
}

static inline int32_t Try_payload_err(const Try* value) {
#if UINTPTR_MAX == UINT64_MAX
    return value->payload.err;
#else
    int32_t payload;
    roc_abi_copy_bytes(&payload, value->payload, sizeof(payload));
    return payload;
#endif
}


// Hosted Function Infrastructure

struct RocOps;

typedef void (*HostedFn)(void);


// Hosted Function Count

#define HOSTED_FUNCTION_COUNT 9


#define HOSTED_IDX_HOST_EX 0
#define HOSTED_IDX_HOST_NORMAL 1
#define HOSTED_IDX_HOST_SEND 2
#define HOSTED_IDX_HOST_EVAL 3
#define HOSTED_IDX_HOST_CALL 4
#define HOSTED_IDX_HOST_REPLY 5
#define HOSTED_IDX_HOST_RECEIVE 6
#define HOSTED_IDX_HOST_LOG 7
#define HOSTED_IDX_HOST_PLUGIN_ID 8

// Argument Structures


/**
 * Arguments for Host.ex!
 * Roc signature: Str => {}
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
} HostExArgs;

/**
 * Arguments for Host.normal!
 * Roc signature: Str => {}
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
} HostNormalArgs;

/**
 * Arguments for Host.send!
 * Roc signature: Str => {}
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
} HostSendArgs;

/**
 * Arguments for Host.eval!
 * Roc signature: Str => Str
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
} HostEvalArgs;

/**
 * Arguments for Host.call!
 * Roc signature: Str, Str => Str
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
    RocStr arg1;
} HostCallArgs;

/**
 * Arguments for Host.reply!
 * Roc signature: I64, Str => {}
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    int64_t arg0;
    RocStr arg1;
} HostReplyArgs;

/**
 * Arguments for Host.receive!
 * Roc signature: I64 => Str
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    int64_t arg0;
} HostReceiveArgs;

/**
 * Arguments for Host.log!
 * Roc signature: Str => {}
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
} HostLogArgs;


// Hosted Symbols

/* Host.ex!: Str => {} */
extern void roc_vim_ex(RocStr arg0);

/* Host.normal!: Str => {} */
extern void roc_vim_normal(RocStr arg0);

/* Host.send!: Str => {} */
extern void roc_vim_send(RocStr arg0);

/* Host.eval!: Str => Str */
extern RocStr roc_vim_eval(RocStr arg0);

/* Host.call!: Str, Str => Str */
extern RocStr roc_vim_call(RocStr arg0, RocStr arg1);

/* Host.reply!: I64, Str => {} */
extern void roc_vim_reply(int64_t arg0, RocStr arg1);

/* Host.receive!: I64 => Str */
extern RocStr roc_vim_receive(int64_t arg0);

/* Host.log!: Str => {} */
extern void roc_vim_log(RocStr arg0);

/* Host.plugin_id!: {} => Str */
extern RocStr roc_vim_plugin_id(void);


// Provided Symbols

/* Entrypoint: main_for_host! */
extern int32_t roc_main(void);


// HostedFunctions Registry

/**
 * Registry of all hosted function implementations.
 * Store each implementation cast to HostedFn.
 */
typedef struct {
    HostedFn host_ex_bang;  /* index 0, C name: host_ex */
    HostedFn host_normal_bang;  /* index 1, C name: host_normal */
    HostedFn host_send_bang;  /* index 2, C name: host_send */
    HostedFn host_eval_bang;  /* index 3, C name: host_eval */
    HostedFn host_call_bang;  /* index 4, C name: host_call */
    HostedFn host_reply_bang;  /* index 5, C name: host_reply */
    HostedFn host_receive_bang;  /* index 6, C name: host_receive */
    HostedFn host_log_bang;  /* index 7, C name: host_log */
    HostedFn host_plugin_id_bang;  /* index 8, C name: host_plugin_id */
} HostedFunctions;


#ifdef __cplusplus
}
#endif

#endif /* ROC_PLATFORM_ABI_H */
